### ISSUE TITLE
Failed to import `datashader`

### ISSUE THREAD

**Issue by jmakov** [holoviz/datashader#1277]
```
import datashader

```

#### Stack traceback and/or browser JavaScript console output
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johan/mambaforge-pypy3/envs/test/lib/python3.9/site-packages/datashader/__init__.py", line 8, in <module>
    from .core import Canvas                                 # noqa (API import)
  File "/home/johan/mambaforge-pypy3/envs/test/lib/python3.9/site-packages/datashader/core.py", line 13, in <module>
    from .utils import Dispatcher, ngjit, calc_res, calc_bbox, orient_array, \
  File "/home/johan/mambaforge-pypy3/envs/test/lib/python3.9/site-packages/datashader/utils.py", line 8, in <module>
    import numba as nb
  File "/home/johan/mambaforge-pypy3/envs/test/lib/python3.9/site-packages/numba/__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/home/johan/mambaforge-pypy3/envs/test/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/home/johan/mambaforge-pypy3/envs/test/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

#### Screenshots or screencasts of the bug in action
env.yaml:
```yaml
name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - datashader
  - holoviews
  - hvplot
  - ipywidgets
  - jupyter-resource-usage
  - jupyterlab
  - jupyterlab_execute_time
  - jupyterlab_widgets
  - jupyterlab-variableinspector
  - nodejs
  - numpy
  - pandas[performance,parquet,feather]
  - pip
  - polars
  - pyarrow
  - pyyaml
  - python >=3.9
  - python-dateutil
  - ray-default
  - setuptools
  - tqdm
```
